# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4
    - name: Set .m2/settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        plugin_groups: '["org.openclover"]'
    - name: Run tests with Maven
      working-directory: backend/
      run: mvn clean clover:setup test clover:aggregate clover:clover
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: backend/target/site/clover/clover.xml
